name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use node
        uses: actions/setup-node@v4
        with:
          node-version: 22.5.1

      - run: npm ci
      - run: npm run build

      - run: ./deploy.sh
        env:
          AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
